# This file was auto-generated by main.py based on your hardware.
# You can rename this file to 'config.py' to use these settings.
# Detected Hardware: 16 CPU cores, GPU: NVIDIA GeForce RTX 3060 Laptop GPU (6.00 GB VRAM)

'''
Auto-generated configuration based on detected hardware.
Rename this file to config.py to use it.
'''

# Low VRAM (< 8GB) detected. Using a smaller model and batch size to prevent memory errors.

CONFIG = {
    # --- Hardware Optimized Settings ---
    'batch_size': 1,  # Physical batch size per device.
    'gradient_accumulation_steps': 64,  # Effective batch size = 1 * 64 = 64
    'visnet_hidden_channels': 64,  # Model complexity. Larger values require more VRAM.
    'processing_num_workers': 16,  # Recommended to match the number of CPU cores.
    'loader_num_workers': 0,  # Set to 0 on Windows for stability, otherwise match CPU cores.

    # --- General Training Hyperparameters ---
    'epochs': 100,
    'learning_rate': 0.0001,
    'train_split': 0.8,
    'dropout_rate': 0.5,
    'gradient_clip_val': 1.0,

    # --- ViSNet Model Specific ---
    # Note: The ViSNet attention mechanism requires that 'visnet_hidden_channels' is divisible by the number of attention heads (default is 8).
    'visnet_lmax': 2,  # Use higher-order spherical harmonics (lmax > 1) for better geometric representation.
    'visnet_num_layers': 4,
    'max_num_neighbors': 32,
    'visnet_cutoff': 5.0,
    'visnet_num_rbf': 64,

    # --- Path & Data Settings ---
    'index_file': r'index/INDEX_general_PL.2020R1.lst',
    'dataset_path': r'PDBbind-2025.8.4/P-L/',
    'processed_data_dir': r'processed_data',
    'force_data_reprocessing': True,
    'data_processing_mode': 'strict',
    'max_atoms': 10000,
    'failed_cases_dir': r'failed_cases',

    # --- Utility & Debugging ---
    'seed': 42,
    'profile': False,
    'debug_mode': True,
    'save_every_n_batches': 1000,
    'manual_save_trigger_file': 'SAVE_NOW.flag',
}
