import os
import platform
import torch

def generate_suggested_config():
    """Generates a complete, hardware-optimized config file with explanations."""
    num_cpu_cores = os.cpu_count() or 1
    rec_proc_workers = num_cpu_cores
    rec_load_workers = 0 if platform.system() == "Windows" else num_cpu_cores

    header_comments = [
        "# This file was auto-generated by main.py based on your hardware.",
        "# You can rename this file to 'config.py' to use these settings."
    ]

    if torch.cuda.is_available():
        gpu_name = torch.cuda.get_device_name(0)
        total_mem_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)
        header_comments.append(f"# Detected Hardware: {num_cpu_cores} CPU cores, GPU: {gpu_name} ({total_mem_gb:.2f} GB VRAM)")
        
        if total_mem_gb < 8:  # Low VRAM
            rec_batch_size = 1
            rec_hidden_channels = 64
            rec_grad_accum = 64
            vram_comment = "# Low VRAM (< 8GB) detected. Using a smaller model and batch size to prevent memory errors."
        elif 8 <= total_mem_gb < 16:  # Medium VRAM
            rec_batch_size = 4
            rec_hidden_channels = 128
            rec_grad_accum = 16
            vram_comment = "# Medium VRAM (8-16GB) detected. Using balanced settings for performance."
        else:  # High VRAM
            rec_batch_size = 8
            rec_hidden_channels = 128
            rec_grad_accum = 8
            vram_comment = "# High VRAM (> 16GB) detected. Using a larger batch size for potentially faster training."
    else:  # CPU only
        header_comments.append(f"# Detected Hardware: {num_cpu_cores} CPU cores, No CUDA GPU.")
        rec_batch_size = 1
        rec_hidden_channels = 64
        rec_grad_accum = 64
        vram_comment = "# No GPU detected. Using minimal settings for CPU training. This will be very slow."

    config_str = f"""'''
Auto-generated configuration based on detected hardware.
Rename this file to config.py to use it.
'''

{vram_comment}

CONFIG = {{
    # --- Hardware Optimized Settings ---
    'batch_size': {rec_batch_size},  # Physical batch size per device.
    'gradient_accumulation_steps': {rec_grad_accum},  # Effective batch size = {rec_batch_size} * {rec_grad_accum} = {rec_batch_size * rec_grad_accum}
    'visnet_hidden_channels': {rec_hidden_channels},  # Model complexity. Larger values require more VRAM.
    'processing_num_workers': {rec_proc_workers},  # Recommended to match the number of CPU cores.
    'loader_num_workers': {rec_load_workers},  # Set to 0 on Windows for stability, otherwise match CPU cores.

    # --- General Training Hyperparameters ---
    'epochs': 100,
    'learning_rate': 0.0001,
    'train_split': 0.8,
    'dropout_rate': 0.5,
    'gradient_clip_val': 1.0,

    # --- ViSNet Model Specific ---
    'visnet_lmax': 2,  # Use higher-order spherical harmonics (lmax > 1) for better geometric representation.
    'visnet_num_layers': 4,
    'max_num_neighbors': 32,
    'visnet_cutoff': 5.0,
    'visnet_num_rbf': 64,

    # --- Path & Data Settings ---
    'index_file': r'index/INDEX_general_PL.2020R1.lst',
    'dataset_path': r'PDBbind-2025.8.4/P-L/',
    'processed_data_dir': r'processed_data',
    'force_data_reprocessing': True,
    'data_processing_mode': 'strict',
    'max_atoms': 10000,
    'failed_cases_dir': r'failed_cases',

    # --- Utility & Debugging ---
    'seed': 42,
    'profile': False,
    'debug_mode': True,
    'save_every_n_batches': 1000,
    'manual_save_trigger_file': 'SAVE_NOW.flag',
}}
"""

    try:
        with open('suggested_config.py', 'w') as f:
            f.write("\n".join(header_comments) + "\n\n" + config_str)
        print("-> Successfully generated 'suggested_config.py' with optimized settings.")
    except IOError as e:
        print(f"-> Error: Could not write to 'suggested_config.py': {e}")

def get_hardware_recommendations(config):
    """Analyzes system hardware and provides configuration recommendations based on the loaded config."""
    recommendations = []
    num_cpu_cores = os.cpu_count() or 1

    if platform.system() == "Windows":
        if config.get('loader_num_workers', 0) > 0:
            recommendations.append(f"- On Windows, it's highly recommended to set 'loader_num_workers' to 0 for stability. Your current value is {config.get('loader_num_workers')}.")
    else:
        if config.get('loader_num_workers') != num_cpu_cores:
            recommendations.append(f"- Your system has {num_cpu_cores} CPU cores. For optimal data loading, consider setting 'loader_num_workers' to {num_cpu_cores}. Your current value is {config.get('loader_num_workers')}.")

    if torch.cuda.is_available():
        gpu_name = torch.cuda.get_device_name(0)
        total_mem_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)
        recommendations.append(f"- GPU Detected: {gpu_name} with {total_mem_gb:.2f} GB VRAM.")

        if total_mem_gb < 8 and (config.get('batch_size', 1) > 2 or config.get('visnet_hidden_channels', 128) > 64):
            recommendations.append("  - Your VRAM is low (< 8GB). Consider a smaller 'batch_size' (e.g., 1-2) and 'visnet_hidden_channels' (e.g., 64) to prevent memory errors.")
        elif 8 <= total_mem_gb < 16:
            recommendations.append("  - Your VRAM is medium (8-16GB). Your current settings might be appropriate. You can experiment with a larger 'batch_size' if you have memory to spare.")
        else:
            recommendations.append("  - Your VRAM is high (> 16GB). You can likely increase 'batch_size' and/or model size for faster training.")
        
        recommendations.append(f"  - Your effective batch size is ({config['batch_size']} * {config['gradient_accumulation_steps']}) = {config['batch_size'] * config['gradient_accumulation_steps']}. Adjust based on VRAM.")
    else:
        recommendations.append("- No CUDA GPU detected. Training on CPU will be very slow.")

    if recommendations:
        print("\n" + "="*70)
        print("--- Hardware-based Configuration Recommendations ---")
        for rec in recommendations:
            print(rec)
        print("--- A 'suggested_config.py' file has been generated with fully optimized settings. ---")
        print("="*70 + "\n")
